version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: parser_excel_app
        volumes:
            - ./:/var/www/html
        depends_on:
            - pgsql
        networks:
            - parser_excel

    nginx:
        image: nginx:1.21
        container_name: parser_excel_nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${APP_PORT:-80}:80"
        depends_on:
            - app
        networks:
            - parser_excel

    redis:
        image: redis
        container_name: parser_excel_redis
        ports:
            - '6379:6379'
        restart: unless-stopped
        networks:
            - parser_excel
        command: redis-server --requirepass ${REDIS_PASSWORD:-password}

    echo_server:
        image: broadcast-echo-server
        container_name: parser_excel_echo_server
        build: ./docker/echo_server
        ports:
            - "6001:6001"
        command: laravel-echo-server start
        depends_on:
            - nginx
        volumes:
            - ./:/work
        working_dir: /work
        networks:
            - parser_excel

    pgsql:
        image: postgres:13.3
        container_name: parser_excel_postgres
        environment:
            POSTGRES_DB: ${DB_DATABASE:-db_name}
            POSTGRES_USER: ${DB_USERNAME:-user}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "${DB_PORT:-5432}:5432"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 200MB
        networks:
            - parser_excel

networks:
    parser_excel:

volumes:
    pgdata:
